### ISSUE TITLE
Possible to extend whitelist to support tags?

### ISSUE THREAD

**Issue by justingood** [arminc/clair-scanner#14]
We currently use multiple tags of base images for different apps. For example, we might have some apps running debian:jessie and others running debian:stretch.

Would it be possible to extend the whitelist to be aware of tags? This would allow us to mark certain CVEs as ok if they were to appear in jessie (since Debian hasn't provided a fix), but not mark them as ok in stretch, where a fix has been released.

**Comment by arminc** [comment]
This should be possible, but I can't give you any date when it will be implemented

**Comment by alex-mohemian** [comment]
I would love that too!
