### ISSUE TITLE
Rescan of image Error

### ISSUE THREAD

**Issue by Joeyn414** [arminc/clair-scanner#15]
If you can help me determine if this bug is related to something other than the clair-scanner than I would be very grateful to close this issue. But here is the issue. I updated my image (joeyn414/centosgauntlt) so I of course wanted to see an updated list of vulnerabilities against the image. I deleted the image from my machine and forced a new pull, after I did that I ran the clair-scanner again and I got this error:

```
panic: runtime error: index out of range

goroutine 15 [running]:
main.getVulnerabilities(0x7fff8c5997dc, 0x15, 0x0, 0x0, 0x0, 0x7fff8c5997dc, 0x15, 0x7fff8c5997f2, 0x9, 0x0)
	/root/go/src/vendor/clair-scanner/main.go:320 +0x60f
main.analyzeImage(0x7fff8c5997b1, 0x16, 0xc420262c80, 0x1c, 0x7fff8c5997dc, 0x15, 0x7fff8c5997f2, 0x9, 0x0, 0x0, ...)
	/root/go/src/vendor/clair-scanner/main.go:118 +0x36b
main.start.func1(0xc4201c3680, 0x7fff8c5997b1, 0x16, 0xc420262c80, 0x1c, 0x7fff8c5997dc, 0x15, 0x7fff8c5997f2, 0x9, 0x0, ...)
	/root/go/src/vendor/clair-scanner/main.go:82 +0xa7
created by main.start
	/root/go/src/vendor/clair-scanner/main.go:83 +0x1ea

```

Any idea what it could be? The error messages as you can see are not helpful.

**Comment by arminc** [comment]
I tried to reproduce it but I can't. Looking at the code all I can see is that somehow the amount of layers 'layerIds' is empty and therefore gives an index out of range. There is no check in 'getImageLayerIds' how many layers there are so something might be wrong there.

So the problem could be related to clair-scanner but it might be that somehow deleting the image broke something, although I can't reproduce it. How did you delete the image?

**Comment by Joeyn414** [comment]
I ran `docker rmi joeyn414/centosgauntlt` to remove the image. I then ran clair-scanner without doing a `docker pull joeyn414/centosgauntlt` and it just spit out the results from before I made a change to my docker image which I confirmed by looking at the hashes of the layers during analysis. I then did a `docker pull joeyn414/centosgauntlt` and then rain clair-scanner again and thats when I got that error. I've even tried to kill the clair and db containers, remove them and reload everything and I still continue to get the same error. All other images still scan ok, but I havent been able to test it on another "updated" container to show before and after vulnerability results.

**Comment by arminc** [comment]
I tried to figure out what is happening but I can not reproduce the bug. When I scan a image and remove it I get a `[CRIT] ▶ Could not save Docker image [alpine:3.5]: Error response from daemon: reference does not exist` 

I am closing the issue for now but if you still have a problem let me know and we can try to figure out together.
