### ISSUE TITLE
clair-scanner command not found

### ISSUE THREAD

**Issue by s-rohil** [arminc/clair-scanner#28]
`docker run -p 5432:5432 -d --name db arminc/clair-db:2017-09-18`

`docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.1`
 I ran these two commands successfully but I get a clair-scanner not found error when trying to execute the test image.
I am using docker for MAC. 

Any help would be appreciated

**Comment by arminc** [comment]
Could you show the full command of clair-scanner you executed and the response?

**Comment by s-rohil** [comment]
Scenario 1
The steps i followed:
I 
docker run -d --name db arminc/clair-db:2017-03-15
docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.1

`clair-scanner nginx:1.11.6-alpine example-nginx.yaml http://localhost:6060 localhost`
`-bash: clair-scanner: command not found`

Scenario 2
Steps I followed:
- cloned the repository into my local directory
- brew install dep
-` make build
go build
clair.go:10:2: cannot find package "github.com/coreos/clair/api/v1" in any of:
	/somepath/src/github.com/coreos/clair/api/v1 (from $GOROOT)
	/somepath/go/src/github.com/coreos/clair/api/v1 (from $GOPATH)`

**Comment by arminc** [comment]
For Scenario 1 you will need to download a release from ->

For Scenario 2 you need to execute the following command to build the go application
```bash
make ensure && make build
```

**Comment by s-rohil** [comment]
I have downloaded clair-scanner. Do i need to download clair as well?

In scenario 2, 
I have downloaded clair-scanner. Do i need to download clair as well?
The commands i run after downloading are..

`make ensure && make build
dep ensure
/path/to/clair-scanner is not within a known GOPATH`

**Comment by arminc** [comment]
I hope you have solved you problem, i am closing the issue. To summarise:

Step 1: Download clair-scanner binnary from the releases page for your OS https://github.com/arminc/clair-scanner/releases

Step 2: Execute the following two commands:
docker run -d --name db arminc/clair-db:2017-03-15
docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.1

Step 3: Run clair-scanner binary that is appropriate for your OS for example mine will be:
./clair-scanner_darwin_amd64 -w example-alpine.yaml --ip IP alpine:3.5

**Comment by yoda96** [comment]
I was getting the same error.
Provide the full name of binary file that you downloaded instead of clair-scanner.
Example:clair-scanner_linux_amd64

**Comment by vaishnavi777** [comment]
Getting below error,
Please help.

'clair-scanner' is not recognized as an internal or external command,
operable program or batch file.
