### ISSUE TITLE
Issues when scanning as part of Jenkins Pipeline job

### ISSUE THREAD

**Issue by Mattsky** [arminc/clair-scanner#34]
Hi folks, I'm having some odd issues with incorporating this into a Pipeline job.

When I run a scan on the Jenkins instance's command line, it completes with no problems, but when I put the scan command into a build step, it scans some of the layers before throwing a 400 error - this is on the same image. The Jenkins instance itself is in a container and is working normally and the Jenkins user has access to the host's Docker socket file (Docker in Docker.)

Does anyone have any ideas what might be causing this? It's the exact same command, only used in two different places - could it be an environment variable or something?

**Comment by arminc** [comment]
Two jobs running at the same time?

I haven't some across this problem. Is it possible for you to test this out on an empty/default Jenkins (in docker) with just a simpel job that scans an image and see what happens?

**Comment by Mattsky** [comment]
Not to worry - I rebuilt everything just as a test and it seems to be working fine now. Guess it was just a weird network hiccup!
