### ISSUE TITLE
Port already allocated error

### ISSUE THREAD

**Issue by s-rohil** [arminc/clair-scanner#35]
I am successfully running clair on my docker host. When i run "docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.1" , i get port already allocated error. 6060 clair container port is mapped to my host.
Does the clair-scanner work if i allocate a different port?

**Comment by arminc** [comment]
Yes it does, you can change it something like 9999:6060 but don't forget to use port 9999 then when running clair-scanner. See commandline option `-c, --clair="http://127.0.0.1:6060"   Clair URL`
