### ISSUE TITLE
Question: arminc/clair-db and arminc/clair-local-scan dockerfiles

### ISSUE THREAD

**Issue by khba** [arminc/clair-scanner#49]
Hello, 

Where can we find the Dockerfiles of the images used in the Doc arminc/clair-db and arminc/clair-local-scan ?
I checked here: https://hub.docker.com/r/arminc/but find only the builds.

Thanks,

**Comment by arminc** [comment]
You can find all the information here: https://github.com/arminc/clair-local-scan

**Comment by khba** [comment]
Yes maybe the doc can be updated, isn't obvious to someone who don't know Travis. Anyway thanks I think the issue can be closed.
