### ISSUE TITLE
clair scanner not reading vulnerabilities from postgres databas

### ISSUE THREAD

**Issue by RamirezTuco** [arminc/clair-scanner#56]
Hello, 

I am using clair-scanner as below.
```

docker run --net=host -d --name db arminc/clair-db:2018-10-17
docker run --net=host --add-host postgres:127.0.0.1 -d --name clair --net=host arminc/clair-local-scan:v2.0.5

```

After this, i can see the data in the database.
```
root@G5:~/test7# docker exec -it db psql -p 5432 -h 127.0.0.1 -U postgres -W
Password for user postgres: 
psql (10.4)
Type "help" for help.

postgres=# select count(*) from vulnerability;
 count  
--------
 193799
(1 row)

postgres=# 

```

But, when i run the below.
`./clair-scanner --ip 127.0.0.1 -c "http://127.0.0.1:6060" node > out.out`

I can see below.

2018/10/18 14:35:16 [INFO] ▶ Start clair-scanner
2018/10/18 14:35:29 [INFO] ▶ Server listening on port 9279
2018/10/18 14:35:29 [INFO] ▶ Analyzing 98f5a0e202a009cfef4103881ed9e5cbc32baf28829b19442ae736b1ac885dd4
2018/10/18 14:35:29 [INFO] ▶ Analyzing f4f196e4a99e1948178173e35b7e6a578aafd85b2f492ea5d50c64249627c5d6
2018/10/18 14:35:29 [INFO] ▶ Analyzing a367adb66eb77538c5be8545dc70a07ce9e2100b29fd26492e8db7c9751d48aa
2018/10/18 14:35:29 [INFO] ▶ Analyzing 8da6f90590bc48fe8c6cc31eaaf94783e4ff281de5a04e8f917e39dedb384701
2018/10/18 14:35:29 [INFO] ▶ Analyzing 322329db1f30f3f24cf4d81c92d9d70216690155da59340f4733ac48fd1b9fa7
2018/10/18 14:35:29 [INFO] ▶ Analyzing 16a3344b19540560ad6c24ce0fbd027dbe0640ef69e20e8f617f5095b1481337
2018/10/18 14:35:29 [INFO] ▶ Analyzing a6ca2fd079b44b4e39e4afe341ff6276a439aadf946d59ad2637a8b2860b8d33
2018/10/18 14:35:29 [INFO] ▶ Analyzing 27bb12affa29d598087edff47abf559c35245135c2277a6b1b7b1f3202fd8b2c
2018/10/18 14:35:29 [WARN] ▶ Image [node] contains 708 total vulnerabilities
2018/10/18 14:35:29 [ERRO] ▶ Image [node] contains 708 unapproved vulnerabilities

Shouldn't clair-scanner read from the database, and report almost 0 errors, or am i doing something wrong?
Thanks in advance.

**Comment by arminc** [comment]
You are not doing anything wrong, clair-scanner it self does not connect the DB it is clair who does that. clair-scanner gives Clair command to scan a container (in your case node). Clair then downloads the container by accessing clair-scanner, when that is done Clair scans the container and finally clair-scanner gets the information from Clair about vulnerabilities and shows them to you.
Hope this helps

**Comment by RamirezTuco** [comment]
Yes, got it. Thanks for the explanation.
